// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA0XOFlLFkEEPkTKEtQEOi2lVossOTuKQ',
    appId: '1:118352937440:web:5f7bd65e32fc6cff402b85',
    messagingSenderId: '118352937440',
    projectId: 'wallet-fam-jo',
    authDomain: 'wallet-fam-jo.firebaseapp.com',
    storageBucket: 'wallet-fam-jo.firebasestorage.app',
    measurementId: 'G-5P4SB7G0MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGCO8_0tJd4eZt7ssawYiAwWwI6J2xzA',
    appId: '1:118352937440:android:15b76fadca5a43e7402b85',
    messagingSenderId: '118352937440',
    projectId: 'wallet-fam-jo',
    storageBucket: 'wallet-fam-jo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61VhFdiKVwLHsveYSmdhPntWOHEM7ND4',
    appId: '1:118352937440:ios:545c4f8a2c78899a402b85',
    messagingSenderId: '118352937440',
    projectId: 'wallet-fam-jo',
    storageBucket: 'wallet-fam-jo.firebasestorage.app',
    iosBundleId: 'com.example.walletFamJo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA61VhFdiKVwLHsveYSmdhPntWOHEM7ND4',
    appId: '1:118352937440:ios:545c4f8a2c78899a402b85',
    messagingSenderId: '118352937440',
    projectId: 'wallet-fam-jo',
    storageBucket: 'wallet-fam-jo.firebasestorage.app',
    iosBundleId: 'com.example.walletFamJo',
  );

}